const { createClient } = require('@supabase/supabase-js');

const url = 'https://jneuumdktavwzdwvcuhf.supabase.co';
const key = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpuZXV1bWRrdGF2d3pkd3ZjdWhmIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3Mzk4MDIzMSwiZXhwIjoyMDg5NTU2MjMxfQ.hJnAuAxHM_LCXi_sELcvwOIpkUx-per0nwtZBaprSrk';
const supabase = createClient(url, key);

async function inspect() {
    const { data, error } = await supabase
        .from('match_analysis_queue')
        .select('metadata')
        .eq('match_id', '2c7944be-f3c4-4429-a0fa-8d3604acd7a7')
        .eq('agente_tag', 'Guxxtavo#easy')
        .single();

    if (error) {
        console.error('Error:', error);
        return;
    }

    // This metadata is what ORACULO-V saved. But wait, I need the RAW match data to see what Henrik API returned.
    // Usually, the worker fetches the match data and passes it to analyzeMatch.
    // If I want to see the RAW match data, I might need to fetch it from the API myself or see if it's cached.
    // BUT, the database output I saw earlier showed `tactical_events` which were generated by the script.
    
    // Let's look at the `metadata` again. 
    // Wait, `oraculo.js` fetches the match data from Henrik API:
    // const url = `https://api.henrikdev.xyz/valorant/v3/match/${matchId}`;
    
    console.log('Keys in metadata:', Object.keys(data.metadata));
    if (data.metadata.raw_data) {
        console.log('Raw data found!');
        const raw = data.metadata.raw_data;
        const round1 = raw.rounds[0];
        console.log('Round 1 Kills:', JSON.stringify(round1.kills, null, 2));
    } else {
        console.log('Raw data NOT found in metadata.');
    }
}

inspect();
