const { supabase } = require('./db');
const { smartFetch } = require('../services/api-client');
const SynergyEngine = require('../services/synergy-engine');
const OraculoService = require('../services/oraculo-service');

async function run() {
    console.log('--- INICIANDO COORDENADOR PROTOCOLO-V ---');
    
    try {
        // 1. Fetch de Roster (Jogadores Acompanhados)
        const { data: roster, error: rosterErr } = await supabase
            .from('players')
            .select('*');
        
        if (rosterErr) throw rosterErr;
        const rosterIds = roster.map(p => p.riot_id);
        const rosterMap = new Map(roster.map(p => [p.riot_id.toLowerCase().replace(/\s/g, ''), p]));

        console.log(`1. Monitorando ${roster.length} agentes no radar...`);

        // 2. Fetch de Partidas Recentes (via API HenrikDev)
        // No ambiente real, buscaríamos para cada jogador. No teste, o mock responde global.
        console.log(`2. Varrendo satélites em busca de novas operações...`);
        const henrikKey = process.env.HENRIK_API_KEY;
        const matchesBatch = new Map();

        // Para o MVP/Teste: pegamos partidas recentes de um jogador âncora ou do mock
        const anchorPlayer = rosterIds[0] || 'ousadia#013';
        const [name, tag] = anchorPlayer.split('#');
        
        try {
            const url = `https://api.henrikdev.xyz/valorant/v3/matches/br/${name}/${tag}`;
            const res = await smartFetch(url, { 'Authorization': henrikKey });
            
            if (res.status === 200) {
                const json = await res.json();
                const matches = json.data || [];
                matches.forEach(m => matchesBatch.set(m.metadata.matchid, m));
            }
        } catch (err) {
            console.error(`   [⚠️] Falha ao consultar API Henrik: ${err.message}`);
        }

        // 3. Processamento de Sinergia e Resultados
        console.log(`3. Calculando Sinergia e Impacto Tático (${matchesBatch.size} partidas)...`);
        const { operations, newSynergyPoints, newDmPoints } = SynergyEngine.processMatchResults(matchesBatch, rosterMap);

        // 4. Persistência de Dados (Upsert de Players e Insert de Operações)
        if (operations.length > 0) {
            console.log(`   [⚡] Sincronizando ${operations.length} novas operações...`);
            
            // Upsert dos Players com novos Scores
            const playersToUpdate = [];
            for (const p of roster) {
                const nId = p.riot_id.toLowerCase().replace(/\s/g, '');
                const addedSynergy = newSynergyPoints[nId] || 0;
                const addedDm = newDmPoints[nId] || 0;

                if (addedSynergy > 0 || addedDm > 0) {
                    playersToUpdate.push({
                        ...p,
                        synergy_score: p.synergy_score + addedSynergy,
                        dm_score_total: (p.dm_score_total || 0) + addedDm,
                        api_error: false, // Flag de integridade para o motor
                        updated_at: new Date().toISOString()
                    });
                }
            }

            if (playersToUpdate.length > 0) {
                const { error: upsertErr } = await supabase.from('players').upsert(playersToUpdate);
                if (upsertErr) console.error(`   [❌] Erro ao atualizar scores: ${upsertErr.message}`);
            }

            // Registro das operações e gatilho do Oráculo
            for (const op of operations) {
                // Tenta inserir a operação (ignora se já existir)
                const { error: opInsErr } = await supabase.from('operations').insert([{
                    id: op.id,
                    map_name: op.map,
                    mode: op.mode,
                    started_at: op.started_at, // Use the timestamp generated by SynergyEngine
                    score: op.score,
                    result: op.result,
                    team_color: op.team_color
                }]);

                // Gatilho Oráculo para Inteligência Tática (Aguardar para garantir persistência)
                if (op.mode === 'Competitive') {
                    try {
                        await OraculoService.processMatchAnalysis(op);
                    } catch (err) {
                        console.error(`   [❌] Falha no gatilho Oráculo: ${err.message}`);
                    }
                }
            }
        }

        // 5. Limpeza de Agentes Inativos (Maintenance)
        console.log('\n4. Manutenção de Sistema...');
        const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();
        await supabase.from('players').delete().eq('synergy_score', 0).lt('created_at', sevenDaysAgo);

        console.log('\n✅ Sincronização concluída com sucesso!');
        console.log('5. Integridade do Oráculo V garantida via REST Bridge.');

    } catch (error) {
        console.error('\n🔥 Erro fatal no Coordenador:', error);
        process.exit(1);
    }
}

async function notificarOperacao(op) {
    console.log(`   [📢] Notificação: Operação ${op.id.substring(0,8)} | Mapa: ${op.map_name} | Modo: ${op.mode}`);
}

if (require.main === module) run();

module.exports = { run };
