- name: Roda o script de extração e API
        run: node update-data.js
        env:
          HENRIK_API_KEY: ${{ secrets.HENRIK_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}

      # APAGUE A ETAPA "Commit das mudanças". O robô não precisa mais dar git push!
